// Define an enum type called MessageType

public enum MessageType {
	START_CONNECTION, PROCESS_CONNECTION, PUBLIC_KEY, PRIVATE_KEY, 
	GET_SECRET_KEY, SECRET_KEY, PROCESS_SECRET_KEY, 
	MESSAGE, JOIN_GROUP, CREATE_GROUP, 
	END_CONNECTION, STOP_SERVER, ADMIN,ACCEPT_SECRET_KEY, 
	GROUP_MESSAGE;
}
